export const TEST_IDS = {
  landing: {
    getStarted: "landing-get-started-btn",
    login: "landing-login-btn",
  },
  auth: {
    emailInput: "auth-email-input",
    passwordInput: "auth-password-input",
    nameInput: "auth-name-input",
    submitBtn: "auth-submit-btn",
    switchToRegister: "auth-switch-register",
    switchToLogin: "auth-switch-login",
  },
  parent: {
    dashboard: "parent-dashboard",
    logoutBtn: "parent-logout-btn",
    switchToKidBtn: "parent-switch-kid-btn",
    addChildBtn: "parent-add-child-btn",
    childCard: "parent-child-card",
    addTaskBtn: "parent-add-task-btn",
    taskItem: "parent-task-item",
    approveTaskBtn: "parent-approve-task-btn",
    rejectTaskBtn: "parent-reject-task-btn",
    missTaskBtn: "parent-miss-task-btn",
    deleteTaskBtn: "parent-delete-task-btn",
    addRewardBtn: "parent-add-reward-btn",
    rewardItem: "parent-reward-item",
    deleteRewardBtn: "parent-delete-reward-btn",
    addConsequenceBtn: "parent-add-consequence-btn",
    consequenceItem: "parent-consequence-item",
    applyConsequenceBtn: "parent-apply-consequence-btn",
    fulfillRedemptionBtn: "parent-fulfill-redemption-btn",
    setPinBtn: "parent-set-pin-btn",
    pinInput: "parent-pin-input",
    tabTasks: "parent-tab-tasks",
    tabRewards: "parent-tab-rewards",
    tabConsequences: "parent-tab-consequences",
    tabActivity: "parent-tab-activity",
    tabSettings: "parent-tab-settings",
  },
  kid: {
    picker: "kid-picker",
    childOption: "kid-child-option",
    home: "kid-home",
    taskItem: "kid-task-item",
    completeTaskBtn: "kid-complete-task-btn",
    tabTasks: "kid-tab-tasks",
    tabRewards: "kid-tab-rewards",
    tabBadges: "kid-tab-badges",
    redeemBtn: "kid-redeem-btn",
    exitKidBtn: "kid-exit-btn",
    pinDigit: "kid-pin-digit",
  },
};
